#!/usr/bin/env python

"""
Companion for GNU Stow. Prints listing of stowed packages.

Copyright (C) 2013 Chris Hiszpanski <chiszp@gmail.com>
"""

def print_stowed(stowdir, target):
    """Returns list of directories that are already stowed"""
    from os import listdir, walk
    from os.path import lexists, join

    # iterate through all packages within stow directory
    for name in listdir(stowdir):
        # path to stowed package 'name'
        src = join(stowdir, name)

        # reset 'file missing' flag
        missing = False

        # check that each file within stow package exists in target
        for root, dirs, files in walk(src):
            for filename in files:
                if not lexists(join(root.replace(src, target), filename)):
                    missing = True
                    break
            if missing:
                break

        # if no files missing, package is assumed to be stowed
        if not missing:
            print name

def main():
    from optparse import OptionParser
    from os import getcwd
    from os.path import dirname

    parser = OptionParser()
    parser.add_option("-d", "--dir", metavar="DIR", dest="stowdir",
                      help="Set stow dir to DIR (default is current dir)",
                      default=getcwd())
    parser.add_option("-t", "--target", metavar="DIR", dest="target",
                      help="Set target to DIR (default is parent of stow dir)",
                      default=dirname(getcwd()))
    (options, args) = parser.parse_args()

    print_stowed(options.stowdir, options.target)

if __name__ == '__main__':
    main()
